$(eval $(call addlib_s,libintercept,$(CONFIG_LIBINTERCEPT)))

CINCLUDES-y += -I$(LIBINTERCEPT_BASE)/include
CINCLUDES-y += -I$(LIBINTERCEPT_BASE)/rpcgen
CXXINCLUDES-y += -I$(LIBINTERCEPT_BASE)/include

LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/intercept.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/transport.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpc/rpc_core.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpc/rpc_xdr.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpc/rpc_probe.c
# Short-term RPC model: generated protocol types/stubs on top of a minimal
# guest-side CLIENT/XDR compatibility runtime and the existing plain TCP
# transport.
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpc/rpc_compat.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpc/rpc_generated.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpcgen/protocol_xdr.c
LIBINTERCEPT_SRCS-y += $(LIBINTERCEPT_BASE)/rpcgen/protocol_clnt.c
